{
    "name": "Smart - Stock Request",
    "summary": "Internal request for stock",
    "version": "15.0.1.0.0",
    "license": "LGPL-3",
    'author': "Smart Support",
    'website': "https://www.smartsupport.tech/",
    "category": "Warehouse Management",
    'application': True,
    'sequence': -98,
    "depends": ["base","base_setup","stock"],
    "data": [
        "security/stock_request_security.xml",
        "security/ir.model.access.csv",
        "views/product.xml",
        "views/stock_request_views.xml",
        "views/stock_request_allocation_views.xml",
        "views/stock_move_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_request_order_views.xml",
        "views/res_config_settings_views.xml",
        "views/stock_request_menu.xml",
        "data/stock_request_sequence_data.xml",
    ],
    "installable": True,
}
